version: '3.8'

services:
  booktify-app:
    container_name: booktify-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE-HOST-ENV: postgres
      DATABASE-NAME-ENV: ${DATABASE-NAME-ENV}
      DATABASE-USERNAME-ENV: ${DATABASE-USERNAME-ENV}
      DATABASE-PASSWORD-ENV: ${DATABASE-PASSWORD-ENV}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

networks:
  default:
    name: postgres-net
    external: true
