version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE-NAME-ENV}
      POSTGRES_USER: ${DATABASE-USERNAME-ENV}
      POSTGRES_PASSWORD: ${DATABASE-PASSWORD-ENV}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pgdata:

networks:
  default:
    name: postgres-net
